import { requireAdmin } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { adminAction } from '@/app/actions';
import ActionForm from '@/components/action-form';
import { Input } from '@/components/ui/input';
export default async function Page() {
 const admin=await requireAdmin();
 const [users,invites]=await Promise.all([prisma.user.findMany({select:{id:true,name:true,username:true,role:true,active:true},orderBy:{createdAt:'desc'}}),prisma.invite.findMany({where:{usedAt:null,expiresAt:{gt:new Date()}},orderBy:{createdAt:'desc'}})]);
 return <div className="space-y-7"><header><h1 className="text-xl font-bold">Kelola akun</h1><p className="text-sm text-muted-foreground">Data keuangan setiap akun tetap pribadi, termasuk dari admin.</p></header><section className="rounded-xl border bg-background p-5 space-y-4"><h2 className="font-semibold">Undang pengguna</h2><ActionForm action={adminAction} label="Buat undangan"><input type="hidden" name="op" value="invite"/><label>Username pengguna<Input name="username" type="text" required minLength={3} maxLength={30} autoComplete="off" /></label></ActionForm></section><section className="space-y-3"><h2 className="font-semibold">Undangan aktif</h2>{!invites.length && <p className="text-sm text-muted-foreground">Belum ada undangan aktif.</p>}{invites.map(i=><article key={i.id} className="rounded-xl border bg-background p-4 space-y-3"><p className="break-all">{i.username}</p><p className="text-sm">Berlaku sampai {i.expiresAt.toISOString().replace('T',' ').slice(0,16)} UTC</p><ActionForm action={adminAction} label="Batalkan undangan" confirm="Batalkan undangan ini?"><input type="hidden" name="op" value="revokeInvite"/><input type="hidden" name="id" value={i.id}/></ActionForm></article>)}</section><section className="space-y-3"><h2 className="font-semibold">Pengguna</h2>{users.map(u=><article key={u.id} className="rounded-xl border bg-background p-4 space-y-4"><div><h3 className="font-medium">{u.name}</h3><p className="break-all text-sm">{u.username} · {u.role} · {u.active?'Aktif':'Nonaktif'}</p></div><ActionForm action={adminAction} label="Buat tautan reset password"><input type="hidden" name="id" value={u.id}/><input type="hidden" name="op" value="reset"/></ActionForm>{u.id!==admin.id && u.role!=='admin' && <div className="flex flex-wrap gap-3">{[['toggle',u.active?'Nonaktifkan akun':'Aktifkan akun'],['revoke','Cabut semua sesi']].map(([op,label])=><ActionForm key={op} action={adminAction} label={label} confirm={`${label}?`}><input type="hidden" name="id" value={u.id}/><input type="hidden" name="op" value={op}/></ActionForm>)}</div>}</article>)}</section></div>;
}
